version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: django_pytest_jenkins_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=django_pytest_jenkins_test
      - POSTGRES_USER=django_pytest_jenkins_test
      - POSTGRES_PASSWORD=django_pytest_jenkins_test
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: django_pytest_jenkins_jenkins
    ports:
      - '8080:8080'
      - '50000:50000'