services:
  postgres:
    image: postgres:16-alpine
    container_name: django_pytest_jenkins_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=django_pytest_jenkins_test
      - POSTGRES_USER=django_pytest_jenkins_test
      - POSTGRES_PASSWORD=django_pytest_jenkins_test
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    container_name: django_pytest_jenkins_jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

volumes:
  jenkins_home: